devtools::install_github("petrikemppainen/LDna")
require(LDna)
LDmat <- structure(c(NA, 0.84, 0.64, 0.24, 0.2, 0.16, 0.44, 0.44, NA, NA, 0.8, 0.28, 0.4, 0.36, 0.36, 0.24, NA, NA, NA, 0.48, 0.32, 0.2, 0.36, 0.2, NA, NA, NA, NA, 0.76, 0.56, 0.6, 0.2, NA, NA, NA, NA, NA, 0.72, 0.68, 0.24, NA, NA, NA, NA, NA, NA, 0.44, 0.24, NA, NA, NA, NA, NA, NA, NA, 0.2, NA, NA, NA, NA, NA, NA, NA, NA), .Dim = c(8L, 8L), .Dimnames = list(c("L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8"), c("L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8")))
ldna <- LDnaRaw(LDmat)
par(mfcol=c(1,1))
clusters <- extractClusters(ldna, min.edges=0, phi=1)
clusters <- extractClusters(ldna, min.edges=0, phi=0.25, rm.COCs=F)

data(LDna)
ldna <- LDnaRaw(r2.baimaii_subs)
clusters <- extractClusters(ldna, min.edges=15, extract=FALSE)
clusters <- extractClusters(ldna, min.edges=0, extract=FALSE)
clusters <- extractClusters(ldna, min.edges=5, phi=5)
clusters <- extractClusters(ldna, min.edges=10, phi=2)
clusters <- extractClusters(ldna, min.edges=15, lambda.lim=1)
clusters <- extractClusters(ldna, min.edges=10, phi=5, rm.COCs=FALSE)
summary <- summaryLDna(ldna, clusters, r2.baimaii_subs)

el <- mat2el(r2.baimaii_subs)
plotLDnetwork(el=el, option=1, threshold=0.4)
par(mfcol=c(2,2))
plotLDnetwork(ldna, el, option=2, clusters=clusters, summary=summary)
plotLDnetwork(ldna, el, option=2, clusters=clusters, summary=summary, full.network=FALSE, include.parent=TRUE, after.merger=FALSE)
plotLDnetwork(ldna, el, option=2, clusters=clusters, summary=summary, full.network=FALSE, include.parent=TRUE, after.merger=TRUE)
plotLDnetwork(ldna, el, option=2, clusters=clusters, summary=summary, full.network=FALSE, include.parent=TRUE, after.merger=FALSE)
plotLDnetwork(ldna, el, option=2, clusters=clusters, summary=summary, full.network=TRUE, after.merger=TRUE)
